try:
    print(x)
except:
    print("Ha ocurrido un error")
